import { NextResponse } from "next/server"

export async function GET(req, res) {
    return NextResponse.json([
        {
            "id": 1,
            "name": "MacBook Air",
            "slug": "macbook-air",
            "image": "/product/mac/mac-card-40-macbook-air-202110.jfif",
            "category": "mac",
            "description": "16-core Neural Engine, Three Thunderbolt 4 ports, HDMI port, SDXC card slot, headphone jack",
            "price": "1199",
            "relesedate": "12/06/22",
            "version": "New",
            "generation": "9th Generation",
            "size": "14-inch",
            "quantity": 1
        },
        {
            "id": 2,
            "name": "iPad Pro",
            "slug": "ipad-pro",
            "image": "/product/ipad/ipad-card-40-pro-202210.jfif",
            "category": "ipad",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "799",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "10.9-inch",
            "quantity": 1
        },
        {
            "id": 3,
            "name": "iPad 10.9``",
            "slug": "ipad-10.9-inch",
            "image": "/product/ipad/ipad-card-40-ipad-202109.jfif",
            "category": "ipad",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "329",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "10.9-inch",
            "quantity": 1
        },
        {
            "id": 4,
            "name": "iPad 10th Gen",
            "slug": "ipad-10th-gen",
            "image": "/product/ipad/ipad-card-40-ipad-202210.jfif",
            "category": "ipad",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "499",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "10th Generation",
            "size": "10.9-inch",
            "quantity": 1
        },
        {
            "id": 5,
            "name": "iPad Mini",
            "slug": "ipad-mini",
            "image": "/product/ipad/ipad-card-40-ipad-mini-202109.jfif",
            "category": "ipad",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "300",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "9th Generation",
            "size": "10.9-inch",
            "quantity": 1
        },
        {
            "id": 6,
            "name": "iPhone 14",
            "slug": "iphone-14",
            "image": "/product/iphone/iphone-card-40-iphone14-202209.jfif",
            "category": "iphone",
            "description": "6‑core CPU with 2 performance and 4 efficiency cores",
            "price": "699",
            "relesedate": "25/07/22",
            "version": "",
            "generation": "",
            "size": "6.1 & 6.7",
            "quantity": 1
        },
        {
            "id": 7,
            "name": "iPhone 15 Plus",
            "slug": "iphone-15-plus",
            "image": "/product/iphone/iphone-card-40-iphone15hero-202309.jfif",
            "category": "iphone",
            "description": "6‑core CPU with 2 performance and 4 efficiency cores",
            "price": "699",
            "relesedate": "25/07/22",
            "version": "New",
            "generation": "",
            "size": "6.1 & 6.7",
            "quantity": 1
        },
        {
            "id": 8,
            "name": "iPhone 15 Pro",
            "slug": "iphone-15-pro",
            "image": "/product/iphone/iphone-card-40-iphone15prohero-202309.jfif",
            "category": "iphone",
            "description": "6‑core CPU with 2 performance and 4 efficiency cores",
            "price": "799",
            "relesedate": "25/07/22",
            "version": "New",
            "generation": "",
            "size": "6.1 & 6.7",
            "quantity": 1
        },
        {
            "id": 9,
            "name": "iPhone 13",
            "slug": "iphone-13",
            "image": "/product/iphone/iphone-card-40-iphone13hero-202309.jfif",
            "category": "iphone",
            "description": "6‑core CPU with 2 performance and 4 efficiency cores",
            "price": "599",
            "relesedate": "25/07/22",
            "version": "",
            "generation": "",
            "size": "6.1 & 6.7",
            "quantity": 1
        },
        {
            "id": 10,
            "name": "iPhone SE",
            "slug": "iphone-se",
            "image": "/product/iphone/iphone-card-40-iphonese-202203.jfif",
            "category": "iphone",
            "description": "6‑core CPU with 2 performance and 4 efficiency cores",
            "price": "429",
            "relesedate": "25/07/22",
            "version": "",
            "generation": "",
            "size": "6.1 & 6.7",
            "quantity": 1
        },
        {
            "id": 11,
            "name": "iPad Air",
            "slug": "ipad-air",
            "image": "/product/ipad/ipad-card-40-air-202203.jfif",
            "category": "ipad",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "599",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "10.9-inch",
            "quantity": 1
        },
        {
            "id": 12,
            "name": "Apple Watch S9",
            "slug": "apple-watch-s9",
            "image": "/product/watch/watch-card-40-s9-202309.jfif",
            "category": "watch",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "399",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 13,
            "name": "Apple Watch U2",
            "slug": "apple-watch-u2",
            "image": "/product/watch/watch-card-40-ultra2-202309.jfif",
            "category": "watch",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "799",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 14,
            "name": "Apple Watch SE",
            "slug": "apple-watch-se",
            "image": "/product/watch/watch-card-40-se-202309.jfif",
            "category": "watch",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "249",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 15,
            "name": "Apple Watch Harmes",
            "slug": "apple-watch-harmas",
            "image": "/product/watch/watch-card-40-hermes-202309.jfif",
            "category": "watch",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "1249",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 16,
            "name": "iPhone 15 Pro case with MagSafe",
            "slug": "iphone-15-pro-case-with-magsafe",
            "image": "/product/accessories/MT4J3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "1249",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 17,
            "name": "iPhone Wallet with MagSafe",
            "slug": "iphone-wallet-with-magsafe",
            "image": "/product/accessories/MT263.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "1249",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 18,
            "name": "20W USB-C Power Adapter",
            "slug": "20w-usb-c-power-adapter",
            "image": "/product/accessories/MU7T2_GEO_US.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "1249",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 19,
            "name": "MagSafe Charger",
            "slug": "magsafe-charger",
            "image": "/product/accessories/MHXH3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "39.00",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 20,
            "name": "Apple Pancil (1st Generation)",
            "slug": "apple-pancil-(1st-generation)",
            "image": "/product/accessories/MK0C2.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "99.00",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "1st Generation",
            "size": "",
            "quantity": 1
        },
        {
            "id": 21,
            "name": "240W USB-C Charge Cable (2m)",
            "slug": "240w-usb-c-charge-cable-(2m)",
            "image": "/product/accessories/MU2G3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "29.00",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 22,
            "name": "USB-C to Lightning Adapter",
            "slug": "usb-c-to-lightning-adapter",
            "image": "/product/accessories/MUQX3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "29.00",
            "relesedate": "23/12/22",
            "version": "New",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 23,
            "name": "Air Pod Pro",
            "slug": "air-pod-pro",
            "image": "/product/accessories/MTJV3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "249",
            "relesedate": "23/12/22",
            "version": "Free Engraving",
            "generation": "2nd Generation",
            "size": "",
            "quantity": 1
        },
        {
            "id": 24,
            "name": "Apple Pancil Adapter",
            "slug": "apple-pancil-adapter",
            "image": "/product/accessories/MQLU3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "9.00",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 25,
            "name": "Smart Folio for iPad",
            "slug": "smart-folio-for-ipad",
            "image": "/product/accessories/MQDT3.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "79.00",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 25,
            "name": "Home Pod-Midnight",
            "slug": "home-pod-midnight",
            "image": "/product/accessories/homepod-select-midnight-202210.png",
            "category": "accessories",
            "description": "64GBFootnote1 From $419 or $34.91/mo.per month for 12 mo.monthsFootnote",
            "price": "299",
            "relesedate": "23/12/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
        {
            "id": 26,
            "name": "MacBook Air 13 and 15",
            "slug": "macbook-air-13-and-15",
            "image": "/product/mac/mac-card-40-macbook-air-13-15-202306.jfif",
            "category": "mac",
            "description": "16-core Neural Engine, Three Thunderbolt 4 ports, HDMI port, SDXC card slot, headphone jack",
            "price": "1099",
            "relesedate": "12/06/22",
            "version": "New",
            "generation": "",
            "size": "13-and-15-inch",
            "quantity": 1
        },
        {
            "id": 27,
            "name": "MacBook Pro 14 and 16",
            "slug": "macbook-pro-14-and-16",
            "image": "/product/mac/mac-card-40-macbook-pro-14-16-202301.jfif",
            "category": "mac",
            "description": "16-core Neural Engine, Three Thunderbolt 4 ports, HDMI port, SDXC card slot, headphone jack",
            "price": "1999",
            "relesedate": "12/06/22",
            "version": "",
            "generation": "",
            "size": "14-and-16-inch",
            "quantity": 1
        },
        {
            "id": 28,
            "name": "Mac Mini",
            "slug": "mac-mini",
            "image": "/product/mac/mac-card-40-mac-mini-202301.jfif",
            "category": "mac",
            "description": "16-core Neural Engine, Three Thunderbolt 4 ports, HDMI port, SDXC card slot, headphone jack",
            "price": "599",
            "relesedate": "12/06/22",
            "version": "",
            "generation": "",
            "size": "",
            "quantity": 1
        },
    ])
}