"use client"

import '../styles/globals.css'
import { Inter } from 'next/font/google'

import GlobalProvider from './redux/provider'

const inter = Inter({ subsets: ['latin'] })

import "bootstrap/dist/css/bootstrap.min.css"

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Apple',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
          <GlobalProvider>
            <Navbar />
            {children}
            <Footer />
          </GlobalProvider>
      </body>
    </html>
  )
}
